services:
  - type: web
    name: laravel-app
    runtime: docker
    plan: free
    envVars:
      - key: APP_ENV
        value: production
      - key: APP_KEY
        sync: false
      - key: DB_CONNECTION
        value: pgsql
      - key: DB_HOST
        value: dpg-cvsuk7c9c44c73c71kd0-a
      - key: DB_PORT
        value: 5432
      - key: DB_DATABASE
        value: laravel_9g38
      - key: DB_USERNAME
        value: laravel_9g38_user
      - key: DB_PASSWORD
        value: nqNsBpZHd27oSN1tWw310vURfGjeXZL1
    buildCommand: |
      composer install --no-dev --optimize-autoloader
    startCommand: |
      php artisan migrate --force && php artisan serve --host=0.0.0.0 --port=10000
    autoDeploy: true
